const countriesOptions = {
  US: { label: "United States", prefix: "1" },
  CA: { label: "Canada", prefix: "1" },
  GB: { label: "United Kingdom", prefix: "44" },
  AU: { label: "Australia", prefix: "61" },
  AT: { label: "Austria", prefix: "43" },
  BS: { label: "Bahamas", prefix: "1" },
  BR: { label: "Brazil", prefix: "55" },
  BG: { label: "Bulgaria", prefix: "359" },
  CN: { label: "China", prefix: "86" },
  DK: { label: "Denmark", prefix: "45" },
  FI: { label: "Finland", prefix: "358" },
  FR: { label: "France", prefix: "33" },
  DE: { label: "Germany", prefix: "49" },
  HK: { label: "Hong Kong", prefix: "852" },
  IN: { label: "India", prefix: "91" },
  IE: { label: "Ireland", prefix: "353" },
  IL: { label: "Israel", prefix: "972" },
  IT: { label: "Italy", prefix: "39" },
  JP: { label: "Japan", prefix: "81" },
  LI: { label: "Lichtenstein", prefix: "423" },
  LT: { label: "Lithuania", prefix: "370" },
  MX: { label: "Mexico", prefix: "52" },
  NL: { label: "Netherlands", prefix: "31" },
  NZ: { label: "New Zealand", prefix: "64" },
  RO: { label: "Romania", prefix: "40" },
  SG: { label: "Singapore", prefix: "65" },
  ZA: { label: "South Africa", prefix: "27" },
  KR: { label: "South Korea", prefix: "82" },
  SE: { label: "Sweden", prefix: "46" },
  CH: { label: "Switzerland", prefix: "41" },
  TH: { label: "Thailand", prefix: "66" },
  AE: { label: "United Arab Emirates", prefix: "971" },
  ES: { label: "Spain", prefix: "34" },
};

export default countriesOptions;
